version: '3'
services:
  web:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - node
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbdata:/var/lib/mysql
  node:
    image: node:16
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm run watch
volumes:
  dbdata:
